from pydantic import BaseModel, EmailStr, Field
from datetime import date, datetime
from typing import Optional

class UserBase(BaseModel):
    email: EmailStr

class UserCreate(UserBase):
    password: str
    # verification_token is generated by backend, not provided by client

class UserRead(UserBase):
    id: int
    is_verified: bool
    verification_token: Optional[str] = None
    avatar_url: Optional[str] = None
    created_at: Optional[datetime] = None

    class Config:
        from_attributes = True

class UserLogin(UserBase):
    password: str

class UserUpdate(BaseModel):
    password: Optional[str] = None
    avatar: Optional[str] = None

class ContactBase(BaseModel):
    first_name: str = Field(min_length=2, max_length=50)
    last_name: str = Field(min_length=2, max_length=50)
    email: EmailStr
    phone: str = Field(min_length=10, max_length=20)
    birthday: date
    additional_data: Optional[str] = None
    user_id: Optional[int] = None

class ContactCreate(ContactBase):
    pass

class ContactUpdate(ContactBase):
    pass

class Contact(ContactBase):
    id: int
    user_id: int

    class Config:
        from_attributes = True
